### PR TITLE
Improve Python templates

### PR DESCRIPTION
**Pull request by bmwilly**
- simplify dependencies
- simplify file structure
- make PEP8 compatible

### CODE REVIEW

**Comment by bmwilly** [comment]
[Improve existing and create new OpenFaaS templates](https://trello.com/c/ejJWRMEx/122-improve-existing-and-create-new-openfaas-templates)

**Review by trusch — COMMENTED** [review]
Looks great! I wonder if it would make sense to move all the static parts (watchdog downloading, initial requirements downloading...) Into a base image. It would greatly reduce build time imo

**Comment by bmwilly** [comment]
@trusch where would that base image live? It's an interesting idea but I'm wary of maintaining another image. And the build times for these aren't too bad.

**Comment by trusch** [comment]
The code should live in this repo, and the base image on dockerhub/quay.io since this repo is opensource iirc.

And to the maintenance concern: this would just move the maintenance requirements to the baseimage since the template itself would get fairly less complex.

It's just a suggestion :)

**Comment by trusch** [comment]
I see that this repo is not opensource, therefore the baseimage should live in both of our gcr registries

**Review by nagautier — APPROVED** [review]
Where did the requirements install go? Could we leave them as a comment to show how it's done?

**Comment by bmwilly** [comment]
@nagautier only one of the two `requirements.txt` files was deleted 
image

**Comment by bmwilly** [comment]
@trusch I think I'll hold off on creating a base image for now since both `fwatchdog` and `requirements.txt` are used by only one template. I'll keep it in mind if there ends up being some common functionality we can factor out.

**Pull request merged**
